# Generated by Django 3.0.8 on 2020-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20200722_1928"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="identification",),
        migrations.AddField(
            model_name="user",
            name="kakao_id",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
