# Generated by Django 3.0.8 on 2020-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20200802_1335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="kakao_id", field=models.IntegerField(),
        ),
    ]
