# Generated by Django 3.0.8 on 2020-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200804_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='asdasd', max_length=128),
            preserve_default=False,
        ),
    ]
