# Generated by Django 3.0.8 on 2020-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200815_0606'),
    ]

    operations = [
    ]
