version: "3"

services:
  db:
    container_name: db
    image: postgres:10.9
    environment:
      - POSTGRES_USER=dpm123
      - POSTGRES_PASSWORD=dpm
      - POSTGRES_DB=warmingup
      - POSTGRES_HOST=localhost
    ports:
      - "${DB_PORT:-4432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    image: app:latest
    depends_on:
      - db
    links:
      - db
    container_name: server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./pgdata:/pgdata
    command: ./scripts/wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000

  migrate:
    image: app:latest
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./pgdata:/pgdata
    command: ./scripts/wait-for-it.sh db:5432 -- python manage.py migrate
