# Generated by Django 3.0.8 on 2020-08-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200728_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
