# Generated by Django 3.0.8 on 2020-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200724_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/img.jpg', upload_to='article/img'),
        ),
    ]
