# Generated by Django 3.0.8 on 2020-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200802_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='media_contents',
            field=models.ManyToManyField(to='article.MediaContent'),
        ),
    ]
