# Generated by Django 3.1 on 2020-08-25 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0011_article_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="address",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
